#! /bin/sh
### BEGIN INIT INFO
# Provides:          opentracker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Opentracker init script
# Description:       This a init script for Opentracker (a bittorrent tracker).
### END INIT INFO

### Configuration // Configuracion ###
#
# Configure file // Archivo de configuracion:
CONF_FILE=/full/path/of/config/file
#
# Opentracker binary // Ejecutable de Opentracker:
BIN=/full/path/of/binary
#
### End of Configuration // Fin de configuracion ###

case "$1" in
  start)
                echo -n "Starting Open Bittorrent Tracker ..."
                $BIN -f $CONF_FILE > /dev/null &
		echo " [ OK ]"
                echo "."
                ;;
  stop)
                echo -n "Stopping Open Bittorrent Tracker"
                 kill `ps auxw | grep "$BIN -f $CONF_FILE" | awk '{print $2}'` > /dev/null
                echo "."
                ;;

  *)
                echo "Usage: /etc/init.d/opentracker {start|stop}"
                exit 1
esac
